### ISSUE TITLE
"Show Diff" action stopped working

### ISSUE THREAD

**Issue by chenop** [codebling/CommunityCase#15]
Hi,

Congratulation on a Great plugin!
I just installed on intellij 13.1 your new v3 version.
Tried to "Show Diff" on a file, and got the following on the "Version Control" console:

09:17:15.945: "C:\Program Files\ibm\RationalSDLC\ClearCase\bin\cleartool.exe" lsh "-last 1" "-fmt \001%Vn\002%Nd\003%En\n\n" -- SomeClass.java
cleartool: Error: Unrecognized option "-last 1"
Usage: lshistory -graphical [-nopreferences [ [-minor] [-nco]
                             [-user login-name]
                             [-branch branch-type-selector] ] ]
                            [ [-recurse | -directory | -all | -avobs]
                             [-pname] pname ...
                             | object-selector ...
                            ]
       lshistory [-long | -short | -fmt format] [-eventid]
                 [-minor] [-nco] [-last [#_lines]]
                 [-since date-time] [-me | -user login-name]
                 [-branch branch-type-selector]
                 [ [-recurse | -directory | -all | -avobs | -local]
                  [-pname] pname ...
                  | object-selector ...
                 ]

**Comment by codebling** [comment]
Thanks I'll fix that right away

**Comment by codebling** [comment]
That's the history browser that failed. Sorry, I was using IntelliJ's "Show Usages" option instead of "Find Usages" and didn't catch all of the usages for the last change I made (if there are too many usages they don't all appear). Should be fixed now
