### ISSUE TITLE
"Version Tree" is not working

### ISSUE THREAD

**Issue by chenop** [codebling/CommunityCase#19]
Hi,
When doing:
Right click --> ClearCase --> Vesion Tree

The version tree does not open.

Got the following message in the "Version Control" window log:
09:51:07.374: cd [my directory]
09:51:07.374: "C:\Program Files\ibm\RationalSDLC\ClearCase\bin\cleartool.exe" "lsvtree -g" -- [my_file]@@
cleartool: Error: Unrecognized command: "lsvtree -g"
09:51:44.025: cd [my_app_root_directory]
09:51:44.026: "C:\Program Files\ibm\RationalSDLC\ClearCase\bin\cleartool.exe" lsco -a -me -cvi --

Saw that in the previous versions the "lsvtree -g" appeared without the "...

**Comment by chenop** [comment]
Any update on this one?

**Comment by codebling** [comment]
Sorry for the extreme delay. Computer was broken. Looks like this is happening with all directives in Command.java that have a space in them. Let's see what we can do...

**Comment by codebling** [comment]
that should do it.

**Comment by chenop** [comment]
Hi,

Thanks for the update!
Just tried to install the plug-in at Intellij 13.1.4 and got:
"Plugin CommunityCase incompatible with current installation"

Am i doing someething wrong?

Thanks!

**Comment by codebling** [comment]
fixed, the compatibility hadn't been updated for 13.1.4, I was testing against 13.1.2 and didn't realise that the version number had gone so high
