### ISSUE TITLE
Unrecognized option "-fmt"

### ISSUE THREAD

**Issue by codebling** [codebling/CommunityCase#3]
Version history generates the following command and error:
 cleartool.exe get -fmt \"\001%Vn\002%Nd\003%En\n\n\" --
 cleartool: Error: Unrecognized option "-fmt"

**Comment by codebling** [comment]
@MarcinKuder how did you trigger this? Were you comparing with an older history version?

**Comment by MarcinKuder** [comment]
Right click on a file, ClearCase->Show History

**Comment by codebling** [comment]
Does the history display correctly? I really need to set up a ClearCase server to test on.. !

**Comment by codebling** [comment]
fixed.
