### ISSUE TITLE
Can't enable ClearCase integrations

### ISSUE THREAD

**Issue by codebling** [codebling/CommunityCase#4]
When enabling ClearCase integrations:
 cleartool.exe NOTIMPLEMENTED_TAG -l
 cleartool: Error: Unrecognized command: "NOTIMPLEMENTED_TAG"
 cleartool.exe NOTIMPLEMENTED_LS_FILES
 cleartool: Error: Unrecognized command: "NOTIMPLEMENTED_LS_FILES"

**Comment by codebling** [comment]
@MarcinKuder What menu action caused this? I don't know what ClearCase integrations are where you found that option!

**Comment by MarcinKuder** [comment]
This action has to be performed (once) in order for the CleareCase to work with an opened project.
From the main menu: VCS -> Enable Version Control Integration -> select ClearCase from a dropdown.

**Comment by codebling** [comment]
aha! I've never enabled it that way - always through Project Settings, Version Control. Though it's possible that those errors come up anyways. So despite those errors, it sounds like you are nonetheless able to activate ClearCase integration?

**Comment by codebling** [comment]
Working as of plugin version 12.1.4-v2
