### ISSUE TITLE
Unrecognized option "--max-count=5"

### ISSUE THREAD

**Issue by codebling** [codebling/CommunityCase#5]
"Changes" window -> "Log" tab:
 cleartool.exe lsh --max-count=5 --all -- .
 cleartool: Error: Unrecognized option "--max-count=5"

**Comment by MarcinKuder** [comment]
Maybe it shall be "-last 5"..
But why show only last 5?

**Comment by codebling** [comment]
fixed 48c249bff3

**Comment by codebling** [comment]
we limit the number of history results returned as there can be a lot of history data
