### ISSUE TITLE
How to install CommunityCase

### ISSUE THREAD

**Issue by chenop** [codebling/CommunityCase#9]
Hi,

I failed to install CommunityCase on my Intellij Community Edition (ver 13.1.1)
Ive tried:
1. Plugins --> "browse repositories" --> searched for CommunityCase -> Nothing was found.
2. download the CommunityCase.jar --> "Install plugin from disk" --> Got: "Plugin CommunityCase is incompatible with current installation".

What am i doing wrong?

**Comment by codebling** [comment]
Nothing! I'll need to make sure that the API hasn't changed and update the plugin !

**Comment by chenop** [comment]
Hi, Any update on this one?

**Comment by codebling** [comment]
So sorry! I've been working on another project, hoping I could get through that before tackling this. I didn't realise it had already been 2 weeks! I'm going to try to quickly fix it right now.

**Comment by codebling** [comment]
Just pushed. The changes for the new API weren't too bad. Testing right now..

**Comment by codebling** [comment]
ClearCase no longer appears in the list of available version control mechanisms, so there must be some other change. Looking into it right now.

**Comment by codebling** [comment]
It must have just been an issue with restarting IntelliJ, the plugin seems to be working at this point. There are a few issues which were not ever fully worked out, we'll deal with those on a case-by-case basis as they come up. Please open a new issue if you run into anything. And please let me know how it goes, positive feedback is direly needed. Thanks!

**Comment by chenop** [comment]
Just tested it and its worked great!
Fantastic job, Thanks!

**Comment by codebling** [comment]
Glad you find it helpful! I don't currently have a good testing environment set up so let me know if you catch any issues
